apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 2                # Runs 2 copies of your container
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app-container
        # This MUST match the image you pushed to DockerHub
        image: udhay36232/vite-react-app:v1
        ports:
        - containerPort: 80