apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: LoadBalancer         # Exposes the app outside the cluster
  selector:
    app: react-app           # Connects to the deployment above
  ports:
    - protocol: TCP
      port: 80               # Port you will type in browser
      targetPort: 80         # Port inside the container (Nginx)